
version: 2


models:
  - name: playing_with_tests
    description: "A starter dbt model"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
      - name: c_mktsegment
        description: "The primary key for this table"
        data_tests:
          -  accepted_values:
              values: ['AUTOMOBILE', 'BUILDING', 'FURNITURE', 'MACHINERY', 'HOUSEHOLD']
models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "customer purchases"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: c_name
        description: "name of the customer"

      - name: nation
        description: "nation customer"
        data_tests:
          - unique
          - not_null
      - name:  total_order_price
        description: "total sum of the orders of the customer"

  - name: cumulative_orders_by_date
    description: "sum of the orders by date "
    columns:
      - name: p_orderdate
        description: "date of the order"

      - name: cumulative_sales
        description: "total price of the orders per date "

    
  - name: incremental_time
    description: "times"